src/main/java/hudson/plugins/scm/koji/client/KojiListBuilds.java
src/main/java/hudson/plugins/scm/koji/model/RPM.java
src/main/resources/hudson/plugins/scm/koji/KojiSCM/help-arch.html
src/test/java/hudson/plugins/scm/koji/client/KojiListBuildsTest.java

Arch field now accepts a list of archs to check for.

Adding support for multiple archs

---

src/main/java/hudson/plugins/scm/koji/client/KojiBuildDownloader.java

Done by recursion. Is it readable? Can redo with loop.

isUrlReachable support 301 redirections

---

src/main/java/org/fakekoji/http/PreviewFakeKoji.java

Make special repo name handeling logic specific to java repos

fixed preview for thermostat-ng

---

fake-koji/src/main/java/org/fakekoji/http/PreviewFakeKoji.java
fake-koji/src/main/java/org/fakekoji/xmlrpc/server/JavaServer.java
fake-koji/src/main/java/org/fakekoji/xmlrpc/server/KojiDownloadServer.java
fake-koji/src/main/java/org/fakekoji/xmlrpc/server/KojiXmlRpcServer.java
fake-koji/src/main/java/org/fakekoji/xmlrpc/server/SshApiService.java
fake-koji/src/test/java/org/fakekoji/xmlrpc/server/core/TestSshApi.java
jenkins-scm-koji-plugin/pom.xml
jenkins-scm-koji-plugin/src/test/java/hudson/plugins/scm/koji/client/KojiListBuildsTest.java

refactoring:
- All "servers" converted to unified form, where instance of class with start/stop methods is used to start them
KojiListBuildsTest:
- Finished/updated/fixed tests for custom builds (fakekoji), by creating "dummy" file/directory structure, on which instance of fakekoji is started.
- Tests which brew are now conditional, based on accessibility of brew server

KojiListBuildsTest: updated/fixed, refactoring of various server classes

---

fake-koji/src/main/java/org/fakekoji/http/PreviewFakeKoji.java
fake-koji/src/main/java/org/fakekoji/xmlrpc/server/JavaServer.java
jenkins-scm-koji-plugin/src/test/java/hudson/plugins/scm/koji/client/KojiListBuildsTest.java

Tohle by mělo spravit ten preview fake-koji. Zkoušel jsem to i na svých falešných datech a OK.
Jo a ty komenty to jsem jen oddělal pozůstatky komentů, které jsem zapoměl oddělat...

Fix broken preview, caused by mistake in refactoring

---

fake-koji/pom.xml
fake-koji/src/test/java/org/fakekoji/xmlrpc/server/core/FakeKojiTestUtil.java
fake-koji/src/test/java/org/fakekoji/xmlrpc/server/core/TestPreview.java
jenkins-scm-koji-plugin/pom.xml
jenkins-scm-koji-plugin/src/test/java/hudson/plugins/scm/koji/client/KojiJenkinsTest.java
jenkins-scm-koji-plugin/src/test/java/hudson/plugins/scm/koji/client/KojiListBuildsTest.java

So today I finally added tests, which test Jenkins SCM koji plugin. During their run fake-koji is started, jenkins project is programmatically created using jenkins rule (found here [1]), scm-koji plugin is set up as SCM, etc.. and jenkins build is scheduled. Expectations on reslut are made based on configuration.
Both tests passed on my machine.  Jenkins prints some stack-traces during startup, I am not sure why... But they does not seem to be fatal nor related to my tests. ( I thing that ConfigValidatorsTests prints them too... )
[1] https://wiki.jenkins.io/display/JENKINS/Unit+Test

Added jenkins tests

---

.gitignore
jenkins-scm-koji-plugin/src/test/java/hudson/plugins/scm/koji/client/KojiListBuildsTest.java
koji-scm-lib/src/main/java/hudson/plugins/scm/koji/client/BuildMatcher.java

Split `pkgName`, get builds for all projects to one `List` and then run blackmagic stream on it. This results in "mixed" builds ordered by time.

jenkins plugin - multiproject support

---

koji-scm-lib/src/main/java/hudson/plugins/scm/koji/model/RPM.java

support for zip files download

---

.travis.yml

build with openjdk8 on travis

---

fake-koji/pom.xml

Add dependency to a common lib to scm plugin

---

fake-koji/src/main/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilder.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/BuildJob.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/Job.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/NamesProvider.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/PullJob.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/TaskJob.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/TestJob.java
fake-koji/src/test/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilderTest.java
fake-koji/src/test/java/org/fakekoji/jobmanager/model/JobTest.java

try search for usages on toString!

Better access toname of job, new method of  getName isntead of misuse of toString

---

fake-koji/src/main/java/org/fakekoji/core/AccessibleSettings.java

Removed comments from previous PR #99

removed useless comment by getters

---

fake-koji/src/main/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilder.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/PullJob.java
fake-koji/src/main/resources/jenkins-templates/vm-post-build-task.xml
fake-koji/src/test/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilderTest.java

fixing https://github.com/judovana/jenkins-scm-koji-plugin/issues/129

Now sending selected  otools variables also to postTask

---

fake-koji/src/main/java/org/fakekoji/jobmanager/model/TestJob.java

Origianlly I had much more complex patch,  I took care for Binary, Binaries,None and sources. However then I realised that it is ultimately wrong - That the binaries/binary and sources are affecting *architecture* field  only.

BINARIES now  effectively overwrite blacklist and whitelist to eat all

---

fake-koji/src/main/java/org/fakekoji/jobmanager/model/TestJob.java
fake-koji/src/main/java/org/fakekoji/jobmanager/project/JDKProjectParser.java

fixing https://github.com/judovana/jenkins-scm-koji-plugin/issues/153

Fixed incorrect deduction of test provider in build+test jobs

---

fake-koji/src/main/java/org/fakekoji/jobmanager/JenkinsJobUpdater.java
fake-koji/src/main/java/org/fakekoji/jobmanager/project/JDKProjectManager.java
fake-koji/src/main/java/org/fakekoji/jobmanager/project/JDKTestProjectManager.java

Before any bulk of jenkins ssh ap calls, wake up jenkins

---

fake-koji/src/main/java/org/fakekoji/jobmanager/model/JDKProject.java
fake-koji/src/main/java/org/fakekoji/jobmanager/model/JDKTestProject.java
fake-koji/src/main/java/org/fakekoji/jobmanager/project/JDKProjectManager.java
fake-koji/src/test/java/org/fakekoji/DataGenerator.java
fake-koji/src/test/java/org/fakekoji/core/utils/OToolBuildParserTest.java
webapp/src/components/configForms/JDKProjectForm.tsx
webapp/src/components/configForms/JDKTestProjectForm.tsx
webapp/src/stores/model.ts

SSIA
https://github.com/judovana/jenkins-scm-koji-plugin/issues/150

Implementation of variables for JDKProject and JDKTestProject

---

fake-koji/src/main/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilder.java
fake-koji/src/main/java/org/fakekoji/model/Task.java
fake-koji/src/main/resources/jenkins-templates/shell-script.xml
fake-koji/src/main/resources/jenkins-templates/task-job.xml
fake-koji/src/main/resources/jenkins-templates/timeoutedshell-script.xml
fake-koji/src/test/java/org/fakekoji/DataGenerator.java
fake-koji/src/test/java/org/fakekoji/jobmanager/JenkinsJobTemplateBuilderTest.java
webapp/src/components/configForms/TaskForm.tsx
webapp/src/stores/model.ts
webapp/src/utils/defaultConfigs.ts
webapp/src/utils/validators.ts

still work in progress. Missing frotnend. Otherwise already woks as expected.

 impelmentation of timeouted task

---

fake-koji/src/main/java/org/fakekoji/core/utils/BuildHelper.java
fake-koji/src/main/java/org/fakekoji/model/OToolBuild.java
fake-koji/src/test/java/org/fakekoji/core/FakeKojiDBTest.java

* fix src arch
* fix nvr of binary rpms
* add tests
* add support for any suffix

Fix bugs in BuildHelper

---

fake-koji/pom.xml
jenkins-scm-koji-plugin/pom.xml
koji-scm-lib/pom.xml
pom.xml

Commented out its inclusion during build, as it is ow quite failing
Canbe run (in individual modules) as mvn spotbugs:check

Added spotbugs

---

fake-koji/src/main/java/org/fakekoji/api/http/rest/OToolService.java
webapp/src/components/formComponents/PlatformRow.tsx
webapp/src/components/formComponents/TaskRow.tsx
webapp/src/components/formComponents/VariantRow.tsx

* Fix deleting jdk test projects - Closes #217 
* Sort variants in gui alphabetically
* Should fix undeterministic behaviour of adding new variants

Small fixes

---

fake-koji/src/main/java/org/fakekoji/core/utils/matrix/MatrixGenerator.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/cell/Cell.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/cell/CellGroup.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/cell/MultiUrlCell.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/cell/UpperCornerCell.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/formatter/Formatter.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/formatter/HtmlFormatter.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/formatter/HtmlSpanningFormatter.java
fake-koji/src/main/java/org/fakekoji/core/utils/matrix/formatter/PlainTextFormatter.java
fake-koji/src/test/java/org/fakekoji/core/utils/matrix/MatrixGeneratorTest.java

multi url cells render to multi <td> elements
same multiple projects

Fix matrix formatter spans

---

fake-koji/src/main/java/org/fakekoji/api/http/rest/GetterAPI.java
webapp/src/App.tsx
webapp/src/components/configForms/JDKProjectForm.tsx
webapp/src/components/configForms/JDKTestProjectForm.tsx
webapp/src/components/formComponents/JobConfigComponent.tsx
webapp/src/components/formComponents/PlatformRow.tsx
webapp/src/components/formComponents/TaskRow.tsx
webapp/src/components/formComponents/VariantRow.tsx
webapp/src/stores/ConfigStore.ts
webapp/src/stores/model.ts
webapp/src/stores/services/ConfigService.ts
webapp/src/utils/createJobName.ts

display jenkins job url under each variant

---

webapp/src/utils/validators.ts

Validator didn't count with case when the list has one element that's an empty string
Closes #238 
Closes #176

Fix string list validator

---

fake-koji/src/test/java/org/fakekoji/api/http/rest/OToolServiceRun.java

Add Windows jre filtering.

---

fake-koji/src/main/java/org/fakekoji/api/http/rest/BumperAPI.java
fake-koji/src/main/java/org/fakekoji/api/http/rest/args/VariantBumpArgs.java
fake-koji/src/main/java/org/fakekoji/jobmanager/bumpers/JobModifier.java
fake-koji/src/main/java/org/fakekoji/jobmanager/bumpers/impl/ProviderBumper.java
fake-koji/src/main/java/org/fakekoji/jobmanager/bumpers/impl/VariantBumper.java
fake-koji/src/test/java/org/fakekoji/jobmanager/bumpers/ProviderBumperTest.java
fake-koji/src/test/java/org/fakekoji/jobmanager/bumpers/VariantBumperTest.java

test is nto tuned, nor is checking naything reasonable

Initial working variant bump

---

fake-koji/src/main/java/org/fakekoji/core/AccessibleSettings.java
fake-koji/src/main/java/org/fakekoji/jobmanager/JenkinsCliWrapper.java
fake-koji/src/main/java/org/fakekoji/server/JavaServer.java
fake-koji/src/test/java/org/fakekoji/DataGenerator.java
fake-koji/src/test/java/org/fakekoji/api/http/rest/OToolServiceRun.java
fake-koji/src/test/java/org/fakekoji/jobmanager/JenkinsSshCliTest.java

Reverts judovana/jenkins-scm-koji-plugin#346
this should be merged asa one big commit

Revert "implemented access to jenkins ssh with certificates"
